# Generated by Django 4.2.7 on 2025-08-06 20:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity_units', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity_rate', models.DecimalField(decimal_places=2, default=8.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('rent_fetched', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('rent_received', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_records', to='flats.renterprofile')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('renter', 'month')},
            },
        ),
    ]
