# Generated by Django 4.2.7 on 2025-08-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_remove_rent_fetched_add_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrecord',
            name='payment_made_by',
            field=models.CharField(blank=True, help_text='Name of the person who made the payment', max_length=100),
        ),
    ]
