# Generated by Django 4.2.7 on 2025-08-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0003_rentrecord_payment_made_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentRecord',
        ),
    ]
