# Generated by Django 4.2.7 on 2025-08-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('renter', 'Renter')], default='Owner', max_length=10),
        ),
    ]
