# Generated by Django 4.2.7 on 2025-08-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('renter', 'Renter')], default='Select', max_length=10),
        ),
    ]
