# Generated by Django 5.2 on 2025-09-08 04:21

from django.db import migrations


def cleanup_user_types(apps, schema_editor):
    """Clean up invalid user_type values"""
    CustomUser = apps.get_model('accounts', 'CustomUser')

    # Update users with 'Select' to 'owner' (assuming they are owners if they signed up)
    CustomUser.objects.filter(user_type='Select').update(user_type='owner')

    # Update any other invalid user types to 'owner' as default
    valid_types = ['owner', 'renter']
    invalid_users = CustomUser.objects.exclude(user_type__in=valid_types)
    invalid_users.update(user_type='owner')


def reverse_cleanup_user_types(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fix_user_type_default'),
    ]

    operations = [
        migrations.RunPython(cleanup_user_types, reverse_cleanup_user_types),
    ]
