# Generated by Django 4.2.7 on 2025-08-07 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'owner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_flats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flat',
            name='flat_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('owner', 'flat_number')},
        ),
    ]
