# Generated by Django 4.2.7 on 2025-08-07 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flats', '0002_add_owner_field_to_flat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renterprofile',
            options={'ordering': ['flat__flat_number', '-is_main_renter', 'full_name']},
        ),
        migrations.AddField(
            model_name='renterprofile',
            name='is_main_renter',
            field=models.BooleanField(default=False, help_text='Main renter who has login access'),
        ),
        migrations.AlterField(
            model_name='renterprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Main user account for this flat (only one per flat)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Roommate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('renter_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommates', to='flats.renterprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
