# Generated by Django 4.2.7 on 2025-08-07 06:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0004_delete_rentrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flats', '0003_alter_renterprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('aadhar_document', models.FileField(blank=True, upload_to='documents/aadhar/')),
                ('pan_document', models.FileField(blank=True, upload_to='documents/pan/')),
                ('other_documents', models.FileField(blank=True, upload_to='documents/other/')),
                ('is_main_renter', models.BooleanField(default=False, help_text='Main renter who has login access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_main_renter', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='RentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity_units', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity_rate', models.DecimalField(decimal_places=2, default=8.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('rent_received', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField(blank=True, help_text='Date when rent was received', null=True)),
                ('payment_made_by', models.CharField(blank=True, help_text='Name of the person who made the payment', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.RemoveField(
            model_name='roommate',
            name='renter_profile',
        ),
        migrations.AddField(
            model_name='flat',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='RenterProfile',
        ),
        migrations.DeleteModel(
            name='Roommate',
        ),
        migrations.AddField(
            model_name='rentrecord',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_records', to='flats.flat'),
        ),
        migrations.AddField(
            model_name='flatmember',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_members', to='flats.flat'),
        ),
        migrations.AddField(
            model_name='flatmember',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Main user account for this flat (only one per flat)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rentrecord',
            unique_together={('flat', 'month')},
        ),
    ]
