# Generated by Django 5.2 on 2025-09-04 18:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_flatmember_rentrecord_remove_roommate_renter_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentrecord',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='rentrecord',
            name='payment_made_by',
        ),
        migrations.RemoveField(
            model_name='rentrecord',
            name='rent_received',
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('online', 'Online Payment')], default='cash', max_length=50)),
                ('payment_by', models.CharField(help_text='Name of the person who made the payment', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('rent_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='flats.rentrecord')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
