# Generated by Django 5.2.6 on 2025-09-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0005_remove_rentrecord_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatmember',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the member', null=True),
        ),
    ]
