# Generated by Django 5.2.6 on 2025-09-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_optimize_indexes'),
        ('flats', '0006_flatmember_notes'),
    ]

    operations = [
    ]
