# Generated by Django 5.2.6 on 2025-09-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0007_merge_0004_optimize_indexes_0006_flatmember_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=6000, max_digits=10),
        ),
    ]
